# Generated by Django 5.0.7 on 2024-08-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_slug_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
